### ISSUE TITLE
remove comments from training data

### ISSUE THREAD

**Issue by cameronbergh** [wangcongcong123/auto_coding#8]
i am currently training reformer on python code, from scratch, and it seems to be struggling the most with the code comments. i read in a paper... i think it was codeBERT? (https://arxiv.org/pdf/2002.08155.pdf) that they remove all comments from the codesearchnet dataset for some part of the training and im starting to think that would make sense. but im not sure how to reliably do that for any programming languages. im wondering if anyone knows of a good library for parsing the languages in the codesearchnet dataset.

**Comment by cameronbergh** [comment]
i think if i were training a model pretrained on text (like gpt2), it would probably be better at learning comments.

**Comment by wangcongcong123** [comment]
Yeah, I agree with you for pre-training a model in more domain-specific to codes. It makes more sense to remove the comments. Concerning the parsing tool, I would suggest you to new an issue asking here: https://github.com/microsoft/CodeBERT/issues

**Comment by cameronbergh** [comment]
i recently found this bit of code which seems like it could be useful for this task, im going to leave it here for now, im super busy lately but i havent forgotten about this project https://code.activestate.com/recipes/578178-colorize-python-sourcecode-syntax-highlighting/?in=user-178123
